title: Krolestwo
url: "https://gg1hz.github.io/krolestwo-journal"
baseurl: "/krolestwo-journal"
theme: minima
markdown: kramdown
encoding: utf-8
permalink: /:year/:month/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag